### PR TITLE
chore: add firestore dependency

### PR DESCRIPTION
**Pull request by kdvuong**
Note: downgrading from gradle 6.5 to 6.1.1.
Issue link: https://github.com/gradle/gradle/issues/14889

### CODE REVIEW

**Comment by kdvuong** [comment]
This seems to work for me locally. You guys should try fetching this branch and build see if it works.

**Review by zhpeng811 — APPROVED** [review]

**Comment by zhpeng811** [comment]
I didn't encounter any issue building locally

**Review by c25vdw — APPROVED** [review]
Everyone should fetch this and try to build to make sure it's not broken. Otherwise I'm good with downgrade if there's no immediate fix for this. Maybe we should be attentive to if the issue disappeared (by when we should all update Gradle)

**Comment by c25vdw** [comment]
merging. 
in case the app doesn't build, do a manual gradle sync https://stackoverflow.com/a/29565362/7358099

**Pull request merged**
