### PR TITLE
create project

### PR DESCRIPTION
**Pull request by Meilin-Lyu**

### CODE REVIEW

**Comment by c25vdw** [comment]
@all I think we should put the project in the root directory instead of the /code dir. Can we check out other's repo and confirm on this?

**Comment by Meilin-Lyu** [comment]
Yes!

**Comment by c25vdw** [comment]
checkout theirs: 
https://github.com/CMPUT301W19T09/SkipTheLibrary 
https://github.com/CMPUT301W19T07/Virtual-Library

@Meilin-Lyu Great. You could try create a new idea project, and then move the `.git/` and `doc/` into that project, it should then be recognized as this repo. or you could create the project, put doc/ in it, then init git and add remote origin, pull, then push.

**Comment by Meilin-Lyu** [comment]
OK I will change it.

**Review by c25vdw — APPROVED** [review]
Looks good to me.

**Comment by kdvuong** [comment]
Add build folder to git ignore?

**Review by kdvuong — APPROVED** [review]
Looks good to me

**Comment by Meilin-Lyu** [comment]
OK how about now?

**Review by zhpeng811 — APPROVED** [review]

**Pull request merged**
