### PR TITLE
feat: store username in auth service

### PR DESCRIPTION
**Pull request by kdvuong**
allow us to get username after log in by doing: `AuthService.getInstance().getCurrentUser().getUsername();`

### CODE REVIEW

**Comment by zhpeng811** [comment]
question: what is displayedName? Original I thought that is the username but now username have its own field

**Comment by kdvuong** [comment]
> question: what is displayedName? Original I thought that is the username but now username have its own field

Display name could be Khang Vuong. Doesn't have to be unique. We can drop it if we dont need it. Username could be khangvuong and has to be unique.

**Comment by zhpeng811** [comment]
> > question: what is displayedName? Original I thought that is the username but now username have its own field
> 
> Display name could be Khang Vuong. Doesn't have to be unique. We can drop it if we dont need it. Username could be khangvuong and has to be unique.

I think we don't need it, currently there's nowhere that the user can set their displayed name. Your call if it needs to be removed in this PR or later on, otherwise it looks good!

**Review by zhpeng811 — APPROVED** [review]

**Review by c25vdw — APPROVED** [review]
lgtm

**Pull request merged**
