### PR TITLE
Profile test

### PR DESCRIPTION
**Pull request by Kii-26**
intent test for edit profile

### CODE REVIEW

**Comment by c25vdw** [comment]
1. note that we are using the test project's database now. So right now the account to log in cannot work. You could go to https://console.firebase.google.com/u/1/project/cmput301bookfriends-testing/overview (the testing project console) to add the user data you want to test.

2. This intent test is editing an email, which means that next time this test runs the email is already the changed one. In the test you can write a clean up function that change it back. Trung has a method that's cleaning up books (`tearDown`) , maybe we can do similar thing here but with users. https://github.com/CMPUT301F20T21/Book_Friends/pull/99/files#diff-0a6e55853e02e91530604ee87eef8c3180c94e5e8e0aa60c274f67f846228e19R112-R123

**Comment by zhpeng811** [comment]
Looks like all tests are missing assert conditions.. without assert conditions the test will only fail if it fails to capture an element

An example of assert condition is to check if the email display field is changed to the updated email after performing the edit

**Comment by Kii-26** [comment]
> 1. note that we are using the test project's database now. So right now the account to log in cannot work. You could go to https://console.firebase.google.com/u/1/project/cmput301bookfriends-testing/overview (the testing project console) to add the user data you want to test.
> 2. This intent test is editing an email, which means that next time this test runs the email is already the changed one. In the test you can write a clean up function that change it back. Trung has a method that's cleaning up books (`tearDown`) , maybe we can do similar thing here but with users. https://github.com/CMPUT301F20T21/Book_Friends/pull/99/files#diff-0a6e55853e02e91530604ee87eef8c3180c94e5e8e0aa60c274f67f846228e19R112-R123

For 1, do you mean I directly add account from the firebase web page? Then run the test?
For 2, I actually edit the email back on profileEditEmailSuccess(), should I do this at the end of all test?

**Comment by c25vdw** [comment]
> For 1, do you mean I directly add account from the firebase web page? Then run the test?
> For 2, I actually edit the email back on profileEditEmailSuccess(), should I do this at the end of all test?
1. Actually, you can use this account:
- username: test
- password: bookfriendstest

2. sorry, I missed that code. right now it should be ok.

**Comment by Kii-26** [comment]
I tried with the username test, but it still cannot log in. And I think there is no "test" account in test project's database. I might miss something...?

**Comment by c25vdw** [comment]
I'm guessing your project didn't have the correct services key for the testing project. Maybe try this https://discord.com/channels/753316752087318739/753317648347037746/774063001539313684, the key files are in pinned message.

**Review by c25vdw — APPROVED** [review]
lgtm

**Review by zhpeng811 — APPROVED** [review]
lgtm

**Pull request merged**
